language: node_js
node_js:
  - "12.14.1"
addons:
  mariadb: '10.4'
cache:
  directories:
  - node_modules
git:
  depth: 3
script:
  - cp .env.example .env
  - npx sequelize-cli db:migrate
  - npx sequelize-cli db:seed:all
after_success:
  - yarn coverage
